version: '3.9'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: psychdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"

  psych-svc:
    build: .
    depends_on:
      - postgres
    ports:
      - "8081:8081"
    environment:
      POSTGRES_DB: psychdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123